apiVersion: v1
kind: ConfigMap
metadata:
  name: stmt-parser-cofig
  namespace: home-stack
data:
  db-schema: home-stack
  db-url: jdbc:mysql://mysql:3306/home-stack?profileSQL=true
  logging-level-com-zaxxer-hikari-HikariConfig: DEBUG
  logging-level-com-zaxxer-hikari: TRACE
  logging-level-com-alok: INFO
  spring-datasource-hikari-minimum-idle: "3"
  spring-datasource-hikari-maximum-pool-size: "10"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-cofig
  namespace: home-stack
data:
  test-config: dummyValue
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: home-stack
data:
  nginx.conf: |
    load_module modules/ngx_http_opentracing_module.so;

    worker_processes  1;

    error_log /var/log/nginx/error.log info;

    events {
       # Limit: Connections with Clinet + COnnections with Worker Servers
       worker_connections  1024;
    }

    http {

       # Turn on tracing for all requests
       opentracing on;

       # Set up Jaeger as the vendor tracer to use
       opentracing_load_tracer /usr/local/lib/libjaegertracing_plugin.so /etc/jaeger-nginx-config.json;

       include       mime.types;
       default_type  application/octet-stream;

       log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
       '$status $body_bytes_sent "$upstream_response_time" "$http_referer" '
       '"$http_user_agent" "$http_x_forwarded_for"';

       access_log /var/log/nginx/access.log main;

       upstream statement-parser {
          server stmtparser-service:8081;

          keepalive 30;
       }

       server {
          # IP whitelisting
          allow 192.168.0.151; # Mac-Book Air
          allow 192.168.0.152;
          allow 192.168.0.153; # iPhone
          allow 192.168.0.154; # motoG
          allow 192.168.0.155; # Mac-Book Pro
          deny all;

          listen 80;
          root   /usr/share/nginx/html;
          index  index.html index.htm;

          opentracing_operation_name $request_method;

          opentracing_tag http_user_agent $http_user_agent;
          opentracing_tag http_uri $request_uri;

          log_subrequest on;

          location / {
             #root   /usr/share/nginx/html;
             #index  index.html index.htm;
             try_files $uri /index.html;

             opentracing_propagate_context;
          }

          location /fin {
             rewrite ^/fin/(.*) /fin/$1 break;
             proxy_pass  	     http://statement-parser/;
             proxy_set_header  Host             $host:8081;
             proxy_set_header  X-Real-IP        $remote_addr;
             proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
             proxy_set_header  Via    		      "nginx";

             proxy_pass_request_body on;
             proxy_pass_request_headers on;

             proxy_http_version 1.1;
             proxy_set_header "Connection" "";

             opentracing_propagate_context;
          }

          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
             root   html;
          }
       }

       include servers/*;
    }