apiVersion: v1
kind: ConfigMap
metadata:
  name: stmt-parser-cofig
  namespace: home-stack
data:
  db-schema: home-stack
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-cofig
  namespace: home-stack
data:
  test-config: dummyValue