apiVersion: v1
kind: ConfigMap
metadata:
  name: stmt-parser-cofig
  namespace: home-stack
data:
  db-schema: home-stack
  db-url: jdbc:mysql://mysql:3306/home-stack
  logging-level-com-zaxxer-hikari-HikariConfig: DEBUG
  logging-level-com-zaxxer-hikari: TRACE
  spring-jpa-show-sql: xyz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-cofig
  namespace: home-stack
data:
  test-config: dummyValue