apiVersion: v1
kind: ConfigMap
metadata:
  name: stmt-parser-cofig
  namespace: home-stack
data:
  db-schema: home-stack
  db-url: jdbc:mysql://mysql.home-stack-db.svc.cluster.local:3306/home-stack
  logging-level-com-zaxxer-hikari-HikariConfig: INFO
  logging-level-com-zaxxer-hikari: INFO
  logging-level-com-alok: DEBUG
  logging-level-root: WARN
  logging-level-org-springframework: INFO
  logging-level-org-springframework-security: INFO
  spring-datasource-hikari-minimum-idle: "2"
  spring-datasource-hikari-maximum-pool-size: "10"
  spring-profiles-active: "prod"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-etl-cofig
  namespace: home-stack
data:
  db-schema: home-stack
  db-url: jdbc:mysql://mysql.home-stack-db.svc.cluster.local:3306/home-stack
  logging-level-com-zaxxer-hikari-HikariConfig: INFO
  logging-level-com-zaxxer-hikari: INFO
  logging-level-com-alok: DEBUG
  logging-level-root: WARN
  logging-level-org-springframework: INFO
  logging-level-org-springframework-security: INFO
  spring-datasource-hikari-minimum-idle: "2"
  spring-datasource-hikari-maximum-pool-size: "10"
  spring-profiles-active: "prod"
  cron-expense: 0 30 */12 * * ?
  cron-tax: 0 5 1 * * ?
  cron-investment: 0 10 1 * * ?
  cron-odion: 0 15 1 * * ?
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-api-cofig
  namespace: home-stack
data:
  db-schema: home-stack
  db-url: jdbc:mysql://mysql.home-stack-db.svc.cluster.local:3306/home-stack
  logging-level-com-zaxxer-hikari-HikariConfig: INFO
  logging-level-com-zaxxer-hikari: INFO
  logging-level-com-alok: DEBUG
  logging-level-org-springframework: INFO
  logging-level-org-springframework-security: INFO
  logging-level-root: WARN
  spring-datasource-hikari-minimum-idle: "2"
  spring-datasource-hikari-maximum-pool-size: "10"
  spring-profiles-active: "prod"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-email-cofig
  namespace: home-stack
data:
  db-schema: home-stack
  db-url: jdbc:mysql://mysql.home-stack-db.svc.cluster.local:3306/home-stack
  logging-level-com-zaxxer-hikari-HikariConfig: INFO
  logging-level-com-zaxxer-hikari: INFO
  logging-level-com-alok: DEBUG
  logging-level-root: WARN
  logging-level-org-springframework: INFO
  logging-level-org-springframework-security: INFO
  spring-profiles-active: "prod"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-event-cofig
  namespace: home-stack
data:
  logging-level-com-alok: DEBUG
  logging-level-root: WARN
  logging-level-org-springframework: INFO
  logging-level-org-springframework-security: INFO
  spring-profiles-active: "prod"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-auth-cofig
  namespace: home-stack
data:
  test: some-test
  spring-profiles-active: prod
  logging-level-com-alok: DEBUG
  logging-level-root: WARN
  logging-level-org-springframework: INFO
  logging-level-org-springframework-security: INFO
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-cofig
  namespace: home-stack
data:
  test-config: dummyValue
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-common-cofig
  namespace: home-stack
data:
  test-config: dummyValue
---