apiVersion: v1
kind: Service
metadata:
  name: home-auth-service
  namespace: home-stack
spec:
  # Service will act as load balancer - selector is matching underling instance(s). There can be one or more Deployment(s) with the same selector label
  selector:
    # XX-YYY
    app: home-auth
  # Defining headless service
  #clusterIP: None
  ports:
    - protocol: TCP
      port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-auth-deployment
  labels:
    # This should be same as Service spec:selector
    # XX-YYY
    app: home-auth
  namespace: home-stack
spec:
  # Will use HPA so commenting the below
  #replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: home-auth
  template:
    metadata:
      labels:
        app: home-auth
        network/db-access: "true"
    spec:
#      nodeSelector:
#        kubernetes.io/hostname: jgte
      containers:
        - name: home-auth-container
          image: alokkusingh/home-auth-service:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /home/auth/actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /home/auth/actuator/health/readiness
              port: 8081
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 10
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            # In Spring Boot, any property can be overridden by an environment variable of the same name,
            # with the characters changed to upper case, and the dots changed to underscores
            - name: OAUTH_GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: home-auth-cofig
                  key: oauth-google-client-id
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: home-api-cofig
                  key: db-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: stmt-user-name
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: stmt-password
            - name: LOGGING_LEVEL_COM_ZAXXER_HIKARI_HIKARICONFIG
              valueFrom:
                configMapKeyRef:
                  name: home-api-cofig
                  key: logging-level-com-zaxxer-hikari-HikariConfig
            - name: LOGGING_LEVEL_COM_ZAXXER_HIKARI
              valueFrom:
                configMapKeyRef:
                  name: home-api-cofig
                  key: logging-level-com-zaxxer-hikari
            - name: LOGGING_LEVEL_COM_ALOK
              valueFrom:
                configMapKeyRef:
                  name: home-api-cofig
                  key: logging-level-com-alok
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORFK
              valueFrom:
                configMapKeyRef:
                  name: home-api-cofig
                  key: logging-level-org-springframework
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORFK_SECURITY
              valueFrom:
                configMapKeyRef:
                  name: home-api-cofig
                  key: logging-level-org-springframework-security
            - name: SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE
              valueFrom:
                configMapKeyRef:
                  name: home-api-cofig
                  key: spring-datasource-hikari-minimum-idle
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
              valueFrom:
                configMapKeyRef:
                  name: home-api-cofig
                  key: spring-datasource-hikari-maximum-pool-size
            - name: APPLICATION_SECURITY_JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: home-auth-cofig
                  key: application-security-jwt-secret
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: home-auth-cofig
                  key: spring-profiles-active
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Kolkata
            type: File
