# Dependency: addons metrics-server
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: home-auth-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: home-auth-deployment
  minReplicas: 2
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
#    - type: Pods
#      pods:
#        metric:
#          name: packets-per-second
#        target:
#          type: AverageValue
#          averageValue: 1k
# TODO: Not able to resolve below Ingress as the Ingress is in different namespace
#    - type: Object
#      object:
#        metric:
#          name: requests-per-second
#        describedObject:
#          apiVersion: networking.k8s.io/v1
#          kind: Ingress
#          name: ingress-home
#        target:
#          type: Value
#          value: 10k
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: home-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: home-api-deployment
  minReplicas: 2
  maxReplicas: 2
  # https://docs.openshift.com/container-platform/4.11/rest_api/autoscale_apis/horizontalpodautoscaler-autoscaling-v2.html#spec-metrics-resource
  # https://docs.openshift.com/container-platform/4.11/rest_api/autoscale_apis/horizontalpodautoscaler-autoscaling-v2.html#spec-metrics-pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
#    - type: Pods
#      pods:
#        metric:
#          name: packets-per-second
#        target:
#          type: AverageValue
#          averageValue: 1k
# TODO: Not able to resolve below Ingress as the Ingress is in different namespace
#    - type: Object
#      object:
#        metric:
#          name: requests-per-second
#        describedObject:
#          apiVersion: networking.k8s.io/v1
#          kind: Ingress
#          name: ingress-home
#        target:
#          type: Value
#          value: 10k
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: home-analytics-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: home-analytics-deployment
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
#    - type: Pods
#      pods:
#        metric:
#          name: packets-per-second
#        target:
#          type: AverageValue
#          averageValue: 1k
# TODO: Not able to resolve below Ingress as the Ingress is in different namespace
#    - type: Object
#      object:
#        metric:
#          name: requests-per-second
#        describedObject:
#          apiVersion: networking.k8s.io/v1
#          kind: Ingress
#          name: ingress-home
#        target:
#          type: Value
#          value: 10k
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: home-email-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: home-email-deployment
  minReplicas: 1
  maxReplicas: 1
  # https://docs.openshift.com/container-platform/4.11/rest_api/autoscale_apis/horizontalpodautoscaler-autoscaling-v2.html#spec-metrics-resource
  # https://docs.openshift.com/container-platform/4.11/rest_api/autoscale_apis/horizontalpodautoscaler-autoscaling-v2.html#spec-metrics-pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: home-search-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: home-search-deployment
  minReplicas: 1
  maxReplicas: 1
  # https://docs.openshift.com/container-platform/4.11/rest_api/autoscale_apis/horizontalpodautoscaler-autoscaling-v2.html#spec-metrics-resource
  # https://docs.openshift.com/container-platform/4.11/rest_api/autoscale_apis/horizontalpodautoscaler-autoscaling-v2.html#spec-metrics-pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80