apiVersion: v1
kind: Service
metadata:
  name: home-event-service
  namespace: home-stack
spec:
  # Service will act as load balancer - selector is matching underling instance(s). There can be one or more Deployment(s) with the same selector label
  selector:
    # XX-YYY
    app: home-event
  # Defining headless service
  #clusterIP: None
  ports:
    - protocol: TCP
      port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-event-deployment
  labels:
    # This should be same as Service spec:selector
    # XX-YYY
    app: home-event
  namespace: home-stack
spec:
  # commenting the replicas as this will be controlled by HPA
  #replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: home-event
  template:
    metadata:
      labels:
        app: home-event
        network/db-access: "false"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: node.kubernetes.io/microk8s-worker
                    operator: In
                    values:
                      - microk8s-worker
      #                - microk8s-controlplane
#      nodeSelector:
#        kubernetes.io/hostname: khbr
      containers:
        - name: home-event-container
          image: alokkusingh/home-event-service:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /home/event/actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 60
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /home/event/actuator/health/readiness
              port: 8081
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 60
            failureThreshold: 3
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          env:
            # In Spring Boot, any property can be overridden by an environment variable of the same name,
            # with the characters changed to upper case, and the dots changed to underscores
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: home-event-cofig
                  key: spring-profiles-active
            - name: LOGGING_LEVEL_COM_ALOK
              valueFrom:
                configMapKeyRef:
                  name: home-event-cofig
                  key: logging-level-com-alok
            - name: LOGGING_LEVEL_ROOT
              valueFrom:
                configMapKeyRef:
                  name: home-event-cofig
                  key: logging-level-root
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORFK
              valueFrom:
                configMapKeyRef:
                  name: home-event-cofig
                  key: logging-level-org-springframework
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORFK_SECURITY
              valueFrom:
                configMapKeyRef:
                  name: home-event-cofig
                  key: logging-level-org-springframework-security
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Kolkata
            type: File