apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: home-db-policy
  namespace: home-stack-db
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: home-stack
          podSelector:
            matchLabels:
              network/db-access: "true"
        - ipBlock:
            cidr: 192.168.1.0/24