apiVersion: v1
kind: Service
metadata:
  name: stmtparser-service
  namespace: home-stack
spec:
  selector:
    app: stmtparser
  # Defining headless service
  #clusterIP: None
  ports:
    - protocol: TCP
      port: 8081
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stmtparser-deployment
  namespace: home-stack
spec:
  serviceName: stmtparser-service
  selector:
    matchLabels:
      app: stmtparser
  replicas: 1
  template:
    metadata:
      labels:
        app: stmtparser
    spec:
      containers:
        - name: stmt-parser-container
          image: alokkusingh/statement-parser:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /fin/actuator/health
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /fin/actuator/health
              port: 8081
            initialDelaySeconds: 21
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
          env:
            # In Spring Boot, any property can be overridden by an environment variable of the same name,
            # with the characters changed to upper case, and the dots changed to underscores
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: stmt-parser-cofig
                  key: db-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: stmt-user-name
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: stmt-password
            - name: LOGGING_LEVEL_COM_ZAXXER_HIKARI_HIKARICONFIG
              valueFrom:
                configMapKeyRef:
                  name: stmt-parser-cofig
                  key: logging-level-com-zaxxer-hikari-HikariConfig
            - name: LOGGING_LEVEL_COM_ZAXXER_HIKARI
              valueFrom:
                configMapKeyRef:
                  name: stmt-parser-cofig
                  key: logging-level-com-zaxxer-hikari
            - name: LOGGING_LEVEL_COM_ALOK
              valueFrom:
                configMapKeyRef:
                  name: stmt-parser-cofig
                  key: logging-level-com-alok
            - name: SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE
              valueFrom:
                configMapKeyRef:
                  name: stmt-parser-cofig
                  key: spring-datasource-hikari-minimum-idle
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
              valueFrom:
                configMapKeyRef:
                  name: stmt-parser-cofig
                  key: spring-datasource-hikari-maximum-pool-size
            - name: IOT_SECURE_TRUSTSTORE-PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: stmt-parser-cofig
                  key: iot-secure-truststore-password
            - name: IOT_SECURE_KEYSTORE-PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: stmt-parser-cofig
                  key: iot-secure-keystore-password
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: stmt-volume
              mountPath: /Users/aloksingh/BankStatements
            #- name: tz-config
            #  mountPath: /etc/localtime
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
      volumes:
        - name: stmt-volume
          hostPath:
            # directory location on host
            path: /home/alok/data/git/BankStatements
            # this field is optional
            type: Directory
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Kolkata
            type: File