apiVersion: v1
kind: Service
metadata:
  name: stmtparser-service
  namespace: home-stack
spec:
  selector:
    app: stmtparser
  ports:
    - protocol: TCP
      port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stmtparser-deployment
  namespace: home-stack
spec:
  selector:
    matchLabels:
      app: stmtparser
  replicas: 1
  template:
    metadata:
      labels:
        app: stmtparser
    spec:
      containers:
        - name: stmt-parser-container
          image: alokkusingh/statement-parser
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: stmt-volume
              mountPath: /Users/aloksingh/BankStatements
      volumes:
        - name: stmt-volume
          hostPath:
            # directory location on host
            path: /home/alok/data/git/BankStatements
            # this field is optional
            type: Directory